# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LingoExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LingoExample
  pod 'Lingo', :path => '../'

  target 'LingoExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LingoExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
