//
//  Lingo.swift
//  Auto-generated by Lingo
//

public struct Lingo {
    
    public struct Navigation {
        
        static var tableName = "Navigation"
        
        public static var next: String {
            return "next".localized(tableName: Lingo.Navigation.tableName)
        }
    }
}
